apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-aap-job
  title: Run AAP Job Template
  description: Self-service form to trigger an AAP job template.
spec:
  owner: platform-team
  type: automation

  parameters:
    - title: AAP Job Inputs
      required:
        - environment
        - server_name
      properties:
        environment:
          type: string
          title: Environment
          description: Target environment (dev, qa, prod)
        server_name:
          type: string
          title: Server Name
          description: Target server for deployment

  steps:
    - id: runJob
      name: Run AAP Job Template
      action: ansible:job:run
      input:
        controllerHost: https://aap.example.com
        controllerUsername: ${{ secrets.AAP_USERNAME }}
        controllerPassword: ${{ secrets.AAP_PASSWORD }}
        jobTemplateName: "Deploy Application"
        extraVars:
          environment: ${{ parameters.environment }}
          server_name: ${{ parameters.server_name }}

  # output:
  #   text: |
  #     AAP job triggered successfully!
  #     View it in AAP: ${{ steps.runJob.output.jobUrl }}
