apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-aap-job
  title: Run AAP Job Template
  description: Self-service form to trigger an AAP job template.
spec:
  owner: platform-team
  type: automation

  parameters:
    - title: AAP Job Inputs
      # required:
      #   - environment
      #   - server_name
      properties:
        token:
          title: Token
          type: string
          description: Oauth2 token
          ui:field: AAPTokenField
          ui:backstage:
            review:
              show: false
        # controllerHost:
        #   type: string
        #   title: Controller URL
        #   default: https://new-aap-aap.apps.cluster-xxf9p.dynamic.redhatworkshops.io
        # controllerUsername:
        #   type: string
        #   title: Controller Username
        # controllerPassword:
        #   type: string
        #   title: Controller Password
          #ui:widget: password      
        organization:
          title: Organization
          description: Select organization
          resource: organizations
          ui:field: AAPResourcePicker
          default:
            id: 1
            name: Default
        jobInventory:
          title: Inventory
          description: Select inventory
          resource: inventories
          ui:field: AAPResourcePicker
          default:
            id: 1
            name: Default
        credentials:
          title: Credentials
          description: Select SCM credential for Private repositories
          resource: credentials
          ui:field: AAPResourcePicker     
        project:
          title: project
          description: Select project
          resource: projects
          ui:field: AAPResourcePicker            
        executionEnvironment:
          title: executionEnv
          description: Select project
          resource: execution-environments
          ui:field: AAPResourcePicker           
                  
        scmType:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: Github
          enum:
            - Github
            - Gitlab          

  output:
    text:
      - title: 'op'
        content: |
          **Job ID:** `${{ parameters.organization }} `            

  steps:
     - id: create-template
       name: Create job template
       action: rhaap:create-job-template
       input:
         token: ${{ parameters.token }}
         deleteIfExist: true
         values:
           templateName: 'Self Service Job Template'
           templateDescription: 'Self Service Job Template'
           scmType: ${{ parameters.scmType }}
           project: ${{ parameters.project }}
           organization: ${{ parameters.organization }}
           jobInventory: ${{ parameters.jobInventory }}
           playbook: 'hello_world.yml'
           executionEnvironment: 'Default execution environment'
           credentials: ${{ parameters.credentials }}
    # - id: launch-job
    #   name: Launch job template
    #   action: rhaap:launch-job-template
    #   input:
    #     token: ${{ parameters.AAP_TOKEN }}
    #     values:
    #       template: "https://new-aap-aap.apps.cluster-xxf9p.dynamic.redhatworkshops.io/api/controller/v2/job_templates/9"



