apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-aap-job
  title: Run AAP Job Template
  description: Self-service form to trigger an AAP job template.
spec:
  owner: platform-team
  type: automation

  parameters:
    - title: AAP Job Inputs
      # required:
      #   - environment
      #   - server_name
      properties:
        controllerHost:
          type: string
          title: Controller URL
          default: https://new-aap-aap.apps.cluster-xxf9p.dynamic.redhatworkshops.io
        controllerUsername:
          type: string
          title: Controller Username
        controllerPassword:
          type: string
          title: Controller Password
          #ui:widget: password      
        AAP_TOKEN:
          type: string
          title: aaptoken

  steps:
    - id: launch-job
      name: Launch job template
      action: rhaap:launch-job-template
      input:
        token: ${{ parameters.AAP_TOKEN }}
        values:
          template: "https://new-aap-aap.apps.cluster-xxf9p.dynamic.redhatworkshops.io/api/controller/v2/job_templates/9"

